explainit/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . views import (
            AccountCreationPageView,
            TermsOfServiceListView,
            AccountActivationView,

            #PROFILE
            UserProfileHomeView,
            UpdateUserProfile,

            #PROFILE PICTURE
            ProfilePicUpdateView,

            #ACCOUNT DETAIL
            AccountDetailView,

            #ACCOUNT FOLLOWERS
            followunfollow,
    )

app_name = "accounts"
urlpatterns = [
    path('register/', AccountCreationPageView, name='register-page'),
    path('activate/<uidb64>/<token>', AccountActivationView, name='activate-account'),
    path('terms-of-serives/', TermsOfServiceListView.as_view(), name='terms-of-service-page'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/account_login_page.html'), name='login-page'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/account_logout_page.html'), name='logout-page'),

    #ACCOUNT_PROFILE
    path("profile/", UserProfileHomeView, name="user-profile-home-view"),
    path("profile/update/", UpdateUserProfile, name="user-profile-update-view"),

    #PROFILE PICTURE
    path("profile/<int:pk>/update_profile_picture/", ProfilePicUpdateView.as_view(), name="user-profile-pic-update-view"),

    #ACCOUNT DETAIL
    path("profile/<int:pk>/", AccountDetailView.as_view(), name="account-detail-view"),

    #ACCOUNT FOLLOWERS
    path("profile/<int:pk>/follow", followunfollow, name="account-follow-unfollow"),

    

]   

explainit/courses/urls.py
from django.urls import path, include
from .views import (OurCourseHomeView,
					OurCourseCreateView,
					CourseDetailView,
					enroll_courses,
					CourseUpdateView,
					CourseDeletionView,
					CourseStudentListView,

					#COURSE ARTICLE
					CourseArticleCreationView,
					CourseArticleUpdateView,
					CourseArticleDeletionView,

					)

app_name = "courses"
urlpatterns = [
	#COURSES
  	path("", OurCourseHomeView.as_view(), name="course-home-view"),
  	path("create/", OurCourseCreateView.as_view(), name="course-create-view"),
  	path("<str:pk>/update", CourseUpdateView.as_view(), name="course-update-view"),
  	path("<str:pk>/delete", CourseDeletionView.as_view(), name="course-deletion-view"),
  	path("<str:pk>/", CourseDetailView.as_view(), name="course-detail-view"),
  	path('<int:pk>/enroll', enroll_courses, name='enroll'),
  	path('<int:pk>/students', CourseStudentListView.as_view(), name='course-students'),
  	#COURSE ARTICLES
  	path("<str:pk>/add_article", CourseArticleCreationView.as_view(), name="article-creation-view"),
  	path("<str:pk>/update_article", CourseArticleUpdateView.as_view(), name="article-update-view"),
  	path("<str:pk>/delete_article", CourseArticleDeletionView.as_view(), name="article-delete-view"),
  	
  
]

explainit/explainit/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.site.site_header = 'ExplainIT-Admin'
urlpatterns = [
    path('', include('homepage.urls')),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('courses.urls')),
    path('questions/', include('qanda.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),

    #PASSWORD
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password/password_reset.html'), name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'),                                                                                  name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explainit/qanda/urls.py
from django.urls import path, include
from .views import (QandaHomeView,
                        #QUESTIONS VIEW IMPORT
                        QuestionCreationView,
                        QuestionUpdateView,
                        QuestionDeletionView,

                        #ANSWER VIEW IMPORT
                        AnswerCreationView,
                        AnswerUpdateView,
                        AnswerDeletionView,

                        #REASKS
                        reask_question,
                        )

app_name = "qanda"
urlpatterns = [
      path("", QandaHomeView.as_view(), name="qanda-home-view"),

      #QUESTIONS
      path('new/', QuestionCreationView.as_view(), name='question-creation-view'),
      path('<int:pk>/update', QuestionUpdateView.as_view(), name='question-update-view'),
      path('<int:pk>/delete', QuestionDeletionView.as_view(), name='question-deletion-view'),

      #ANSWERS
      path('answer/<int:pk>/add_answer', AnswerCreationView.as_view(), name='answer-creation-view'),
      path('answer/<int:pk>/update', AnswerUpdateView.as_view(), name='answer-update-view'),
      path('answer/<int:pk>/delete', AnswerDeletionView.as_view(), name='answer-deletion-view'),

      #REASKS
      path('<int:pk>/enroll/', reask_question, name='reask'),
]

explainit/courses/forms.py
from django import forms
from .models import OurCourse, CourseArticle

class OurCourseCreationForm(forms.ModelForm):
	'''
		A model form to be rendered on template
		to create a new course
	'''
	class Meta:
		model 		= OurCourse
		fields  	= ['course_title', 'course_description', 'course_poster']

class OurCourseUpdateForm(forms.ModelForm):
	'''
		A model form to be rendered on template
		to update a course information
	'''
	class Meta:
		model 		= OurCourse
		fields  	= ['course_title', 'course_description', 'course_poster']


class CourseArticleCreationForm(forms.ModelForm):
	'''
		A model form to be rendered on template
		to create a course article 
	'''
	class Meta:
		model 		= CourseArticle
		fields  	= ['article_content', 'article_identity_number']

explainit/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import OurCourse, CourseArticle
from .forms import OurCourseCreationForm, CourseArticleCreationForm
from django.views.generic import (ListView,
									CreateView,
									DetailView,
									UpdateView,
									DeleteView,
									)
from django.contrib.auth.mixins import (LoginRequiredMixin,
										UserPassesTestMixin,
										)
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.cache import cache
from hitcount.views import HitCountDetailView

class OurCourseHomeView(ListView):
	'''
	 A class based view to show lists of
	 all couses on courses homepage
	'''
	model 			= OurCourse
	template_name 	= 'courses/our_courses_home_view.html'


	def get_context_data(self, *args, **kwargs):
		'''
			A django built in func to handle what will be passed
			to the template as what
		'''
		our_courses = OurCourse.objects.all()
		if cache.get('our_courses'):
			our_courses = cache.get('our_courses')
		else:
			cache.set('our_courses', our_courses)
			our_courses = cache.get('our_courses')
		context = super(OurCourseHomeView, self).get_context_data(*args, **kwargs)
		context['title'] = "ExplainIT-Courses"
		context['our_courses'] = our_courses
		return context

class OurCourseCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
	'''
	 A class based view used to create a course
	'''
	model 			= OurCourse
	form_class		= OurCourseCreationForm
	template_name 	= 'courses/course_creation_page.html'


	def form_valid(self, form):
		'''
		 Take the authenticated user as course instructor
		 '''
		form.instance.course_instructor = self.request.user
		messages.success(self.request, 'Course created successfully')
		return super().form_valid(form)

	def get_context_data(self, *args, **kwargs):
		'''
			A django built in func to handle what will be passed
			to the template as what
		'''
		context = super(OurCourseCreateView, self).get_context_data(*args, **kwargs)
		context['title'] = f'{self.request.user.username}-Create-Course'
		return context

	def test_func(self):
		'''
		who can create a course
		'''
		if self.request.user.is_our_teacher or self.request.user.is_admin:
			return True
		return False

class CourseDetailView(HitCountDetailView, DetailView):
	model 			= OurCourse
	template_name	= 'courses/our_course_detail_view.html'
	count_hit		= True
	def get_context_data(self, *args, **kwargs):
		'''
		what should be sent to course detail view page
		'''
		course 	= self.get_object()
		if cache.get('course'):
			course = cache.get('course')
		else:
			cache.set('course', course)
			course = cache.get('course')

		context = super(CourseDetailView, self).get_context_data(*args, **kwargs)
		context['title'] = course.course_title
		context['course'] = course
		return context


class CourseUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	'''
	A CBV to update the course information
	'''
	model = OurCourse
	form_class = OurCourseCreationForm
	template_name = 'courses/course_info_update_view.html'
    
	def form_valid(self, form):
		'''
		What will happen if the form is valid
		'''
		form.instance.course_instructor = self.request.user
		messages.success(self.request, 'Course updated successfully')
		return super().form_valid(form)

	def test_func(self):
		'''
		who can update a course
		'''
		course = self.get_object()
		if self.request.user == course.course_instructor:
			return True
		return False

	def get_context_data(self, *args, **kwargs):
		'''
		what should be sent to course update page
		'''
		context = super(CourseUpdateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Update-course'
		return context

class CourseDeletionView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	'''
	A CBV to delete a course
	'''
	model = OurCourse
	template_name = 'courses/course_deletion_confirm_view.html'

	def get_success_url(self):
		'''
		where to redirect the user after successful deletion of the course
		'''
		course = self.get_object()
		return reverse( 'courses:course-home-view')

	def form_valid(self, form):
		'''
		What will happen if the form is valid
		'''
		messages.success(self.request, 'Course deleted successfully')
		return super().form_valid(form)

	def test_func(self):
		'''
		who can delete a course
		'''
		course = self.get_object()
		if self.request.user == course.course_instructor:
			return True
		return False

	def get_context_data(self, *args, **kwargs):
		'''
		what should be sent to course deletion page
		'''
		course = OurCourse.objects.get(pk=self.kwargs['pk'])
		context = super(CourseDeletionView, self).get_context_data(*args, **kwargs)
		context['title'] = f'{course.course_title} - delete'
		context['course'] = course
		return context


class CourseArticleCreationView(LoginRequiredMixin, CreateView):
	'''
	A CBV to manage the article creation to a course
	'''
	model = CourseArticle
	form_class = CourseArticleCreationForm
	template_name = 'course_articles/course_article_creation_view.html'


	def form_valid(self, form):
		'''
		What will happen if the form is valid
		'''
		form.instance.course_id = self.kwargs['pk']
		form.instance.article_author = self.request.user
		messages.success(self.request, 'Article added successfully')
		return super().form_valid(form)

	def test_func(self):
		'''
		who can create an article
		'''
		course = self.get_object()
		if self.request.user == course.course_instructor and self.request.user.is_our_teacher:
			return True
		return False	

	def get_context_data(self, *args, **kwargs):
		'''
		what should be sent to article craetion page
		'''
		course = OurCourse.objects.get(pk=self.kwargs['pk'])
		context = super(CourseArticleCreationView, self).get_context_data(*args, **kwargs)
		context['title'] = f'{course.course_title} - Add-article'
		context['course'] = course
		return context


class CourseArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	'''
	A CBV to update an article of a course
	'''
	model = CourseArticle
	form_class = CourseArticleCreationForm

	template_name = 'course_articles/course_article_update_view.html'

	def form_valid(self, form):
		'''
		What will happen if the form is valid
		'''
		messages.success(self.request, 'Article updated successfully')
		return super().form_valid(form)

	def test_func(self):
		'''
		who can update an article
		'''
		article = self.get_object()
		if self.request.user == article.course.course_instructor:
			return True
		return False

	def get_context_data(self, *args, **kwargs):
		'''
		what should be sent to the article update page
		'''
		context = super(CourseArticleUpdateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Update-article'
		return context


class CourseArticleDeletionView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	'''
	A CBV to delete an article
	'''
	model = CourseArticle
	template_name = 'course_articles/course_article_deletion_view.html'

	def get_success_url(self):
		'''
		Where to redirect the user after successful deletion
		of an article
		'''
		article = self.get_object()
		return reverse( 'courses:course-detail-view', args=[article.course.pk])

	def form_valid(self, form):
		'''
		What will happen if the form is valid
		'''
		messages.success(self.request, 'Article deleted successfully')
		return super().form_valid(form)


	def test_func(self):
		'''
		who can delete an article
		'''
		article = self.get_object()
		if self.request.user == article.course.course_instructor:
			return True
		return False

	def get_context_data(self, *args, **kwargs):
		'''
		what should be sent to the deletion page
		'''
		article = CourseArticle.objects.get(pk=self.kwargs['pk'])
		context = super(CourseArticleDeletionView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Delete-article'
		context['article'] = article
		return context


@login_required
def enroll_courses(request, pk):
	'''
	enroll or uneroll course
	'''
	if request.method == 'GET':
		user = request.user
		course = get_object_or_404(OurCourse, pk=pk)

		if course.students.filter(id=user.id).exists():
			#user has already enrolled the course
			#remove students from enrolled student list
			course.students.remove(user)
			message=messages.success(request,f'You stopped learning {course.course_title}')
		else:
			course.students.add(user)
			message =messages.success(request, f'You enrolled {course.course_title}')
			total_students = {'total_students':course.total_students}
			return redirect(request.META.get('HTTP_REFERER'))
	return redirect(request.META.get('HTTP_REFERER'))

class CourseStudentListView(DetailView):
	model 			= OurCourse
	template_name	= 'courses/course_student_list_view.html'

	def get_context_data(self, *args, **kwargs):
		'''
		what should be sent to course student list page
		'''
		course 	= self.get_object()

		context = super(CourseStudentListView, self).get_context_data(*args, **kwargs)
		context['title'] = f'{course.course_title}-Students'
		context['course'] = course
		return context

explainit/courses/templates/courses/course_creation_page.html
{% extends 'homepage/base.html'%}
{% load crispy_forms_tags %}
{% block mainbody%}

<section class="course-home-section">
    <section class="all-form-container">
        <section class="all-form-section">
            <fieldset>
            <form method="POST" enctype="multipart/form-data">
                    <header class="form-header">
                        <h2>Course info</h2>
                    </header>
                    <hr>
                    {% csrf_token %}
                    {{ form.media }}
                    {{form|safe}}
                <div class="form-button">
                    <button type="submit">Add</button>
                </div>
            </form>
            </fieldset>
        </section>
    </section>
</section>
{% endblock mainbody%}

explainit/courses/templates/courses/course_deletion_confirm_view.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block mainbody%}
<section class="form-container-section">
    <section class="all-form-container">
        <section class="all-form-section">
            <fieldset>
            <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                    <header class="form-header">
                        <h2>Delete course</h2>
                    </header>
                    <hr>
                    <p>Are you shure you want to delete this course?</p>
                <div class="form-button">
                    <button type="submit">Yes delete</button>
                      <a class="btn btn-outline-secondary" href="{% url 'courses:course-detail-view' course.pk %}">Cancel</a>
                </div>
            </form>
            </fieldset>
        </section>
    </section>
</section>

{%endblock mainbody%}

explainit/courses/templates/courses/course_info_update_view.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block mainbody%}
<section class="form-container-section">
    <section class="all-form-container">
        <section class="all-form-section">
            <fieldset>
            <form method="POST" enctype="multipart/form-data">
                    <header class="form-header">
                        <h2>Course info</h2>
                    </header>
                    <hr>
                    {% csrf_token %}
                    {{ form.media }}
                    {{form|safe}}
                <div class="form-button">
                    <button type="submit">Update course</button>
                </div>
                
            </form>
            </fieldset>
        </section>
    </section>
</section>

{%endblock mainbody%}

explainit/courses/templates/courses/course_student_list_view.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block mainbody%}
{% load humanize %}
<section class="auth-section">
	<div class="center-content">
		{% for student in course.students.all %}
		<article class="question-container">
			<header class="question-header">
				<div class="user-pp">
					<img src="{{student.profile_pic.image.url}}">
				</div>
				<div class="about-question-author">
					<a href="{% url 'accounts:account-detail-view' student.pk %}">{{student.full_name}}</a>
					<small>

					</small>
				</div>
			</header>
			{%endfor%}
		</article>
	</div>
</section>

{%endblock mainbody%}

explainit/courses/templates/courses/our_course_detail_view.html
{% extends 'homepage/base.html' %}
{% block mainbody %}
{% load static %}
{% load hitcount_tags %}
<!-- OUR COURSES STARTS HERE -->
<section class="course-detail-container">
    <div class="course-article-header-container">
       <div class="course-header">
           <small><a>{{course.course_title}}
            {% get_hit_count for course %}-views</a></small>
           <small>By <a href="{% url 'accounts:account-detail-view' course.course_instructor.pk %}"><strong>{{course.course_instructor.full_name}}</strong></a></small>
           <small><a href="{% url 'courses:course-students' course.pk %}">
            {% if course.total_students != 0%}
              {{course.total_students}}-students 
            {% endif %}
            </a>
          </small>
            <small><i>Published on {{course.date_created}}</i></small>
            {% if user == course.course_instructor %}
            <small><a href="{% url 'courses:course-update-view' course.pk %}">Update</a> <a href="{% url 'courses:course-deletion-view' course.pk %}">Delete</a>  <a href="{% url 'courses:article-creation-view' course.pk %}">Add article</a></small>
            {% endif %}
       </div>
       <div class="enroll">
            <a href="{% url 'courses:enroll' course.pk %}">
                {% if user in course.students.all %}
                    <b>Enrolled</b>
                {% else %}
                    Enroll
                {% endif %}
            </a>
       </div>
    </div>  
    <div class="course-detail-article">
        <p>{{course.course_description|safe}}</p>
    </div>
    <hr>
    
    {% for article in course.articles.all %}
      <div class="course-detail-article">
          {{article.article_content|safe}}
          {% if user == article.course.course_intsructor %}
          <small><a href="{% url 'courses:article-update-view' article.pk %}">edit</a>
          </small>
          <small>
           <a href="{% url 'courses:article-delete-view' article.pk %}">delete</a> 
          </small>
          {% endif %}
      </div>
    {% endfor %}
   
</section>

{% endblock mainbody%}

explainit/courses/templates/courses/our_courses_home_view.html
{% extends 'homepage/base.html' %}
{% block mainbody %}
{% load static %}
<!-- User course starts here -->
{% if user.is_our_teacher %}
<div class="add-course">
  <div class="add-course-left">
  </div>
  <div class="add-course-right">
    <a href="{% url 'courses:course-create-view' %}"><img src="{% static 'images/upload.png' %}"></a>
  </div>
</div>
<section class="course-home-section">
	{% for course in user.course.all %}
		<article class="course-article-container">
            <div class="course-article-header-container">
               <div class="course-header">
                   <small><a href="{% url 'courses:course-detail-view' course.pk %}">{{course.course_title}}</a></small>
                   <small>By <a href="{% url 'accounts:account-detail-view' user.pk %}"><strong>{{course.course_instructor.full_name}}</strong></a></small>
               </div>
               <div class="enroll">
               		<p><a href="">Enroll</a></p>
               </div>
            </div>   
            <div class="article-body-container">
            	<a href="{% url 'courses:course-detail-view' course.pk %}">
	                <div class="course-poster">
	                    <p><img src="{{course.course_poster.url}}"></p>
	                </div>
            	</a>
            </div>  
        </article>
    {% endfor %}
</section>
{% endif %}
<!-- User course ends here -->

<!-- OUR COURSES STARTS HERE -->
<section class="course-home-section">
	{% for course in our_courses %}
        <article class="course-article-container">
            <div class="course-article-header-container">
               <div class="course-header">
                   <small><a href="{% url 'courses:course-detail-view' course.pk %}">{{course.course_title}}</a></small>
                   <small>By <a href="{% url 'accounts:account-detail-view' course.course_instructor.pk %}"><strong>{{course.course_instructor.full_name}}</strong></a></small>
               </div>
               <div class="enroll">
               		<p><a href="{% url 'courses:course-detail-view' course.pk %}">Enroll</a></p>
               </div>
            </div>   
            <div class="article-body-container">
            	<a href="{% url 'courses:course-detail-view' course.pk %}">
	                <div class="course-poster">
	                    <p><img src="{{course.course_poster.url}}"></p>
	                </div>
            	</a>
            </div>  
        </article>
    {% endfor %}
</section>
<!-- OUR COURSES ENDS HERE -->

{% endblock mainbody%}