explainit/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . views import (
            AccountCreationPageView,
            TermsOfServiceListView,
            AccountActivationView,

            #PROFILE
            UserProfileHomeView,
            UpdateUserProfile,

            #PROFILE PICTURE
            ProfilePicUpdateView,

            #ACCOUNT DETAIL
            AccountDetailView,

            #ACCOUNT FOLLOWERS
            followunfollow,
    )

app_name = "accounts"
urlpatterns = [
    path('register/', AccountCreationPageView, name='register-page'),
    path('activate/<uidb64>/<token>', AccountActivationView, name='activate-account'),
    path('terms-of-serives/', TermsOfServiceListView.as_view(), name='terms-of-service-page'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/account_login_page.html'), name='login-page'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/account_logout_page.html'), name='logout-page'),

    #ACCOUNT_PROFILE
    path("profile/", UserProfileHomeView, name="user-profile-home-view"),
    path("profile/update/", UpdateUserProfile, name="user-profile-update-view"),

    #PROFILE PICTURE
    path("profile/<int:pk>/update_profile_picture/", ProfilePicUpdateView.as_view(), name="user-profile-pic-update-view"),

    #ACCOUNT DETAIL
    path("profile/<int:pk>/", AccountDetailView.as_view(), name="account-detail-view"),

    #ACCOUNT FOLLOWERS
    path("profile/<int:pk>/follow", followunfollow, name="account-follow-unfollow"),

    

]   

explainit/explainit/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.site.site_header = 'ExplainIT-Admin'
urlpatterns = [
    path('', include('homepage.urls')),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('courses.urls')),
    path('questions/', include('qanda.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),

    #PASSWORD
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password/password_reset.html'), name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'),                                                                                  name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explainit/qanda/urls.py
from django.urls import path, include
from .views import (QandaHomeView,
                        #QUESTIONS VIEW IMPORT
                        QuestionCreationView,
                        QuestionUpdateView,
                        QuestionDeletionView,

                        #ANSWER VIEW IMPORT
                        AnswerCreationView,
                        AnswerUpdateView,
                        AnswerDeletionView,

                        #REASKS
                        reask_question,
                        )

app_name = "qanda"
urlpatterns = [
      path("", QandaHomeView.as_view(), name="qanda-home-view"),

      #QUESTIONS
      path('new/', QuestionCreationView.as_view(), name='question-creation-view'),
      path('<int:pk>/update', QuestionUpdateView.as_view(), name='question-update-view'),
      path('<int:pk>/delete', QuestionDeletionView.as_view(), name='question-deletion-view'),

      #ANSWERS
      path('answer/<int:pk>/add_answer', AnswerCreationView.as_view(), name='answer-creation-view'),
      path('answer/<int:pk>/update', AnswerUpdateView.as_view(), name='answer-update-view'),
      path('answer/<int:pk>/delete', AnswerDeletionView.as_view(), name='answer-deletion-view'),

      #REASKS
      path('<int:pk>/enroll/', reask_question, name='reask'),
]

explainit/accounts/forms.py
from .models import (Account,
                        ProfilePic,
                        UserBio,
                        )
from django import forms
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    '''
    Form class for user registration
    '''
    gender_choices = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('N', 'Other'),
        )
    email 				= forms.EmailField(max_length = 70)
    username 			= forms.CharField(max_length = 30)
    first_name			= forms.CharField(max_length = 30)
    Phone_Number 		= forms.CharField(max_length=12)
    birth_date          = forms.DateTimeField()
    gender              = forms.ChoiceField(choices=gender_choices)
    
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'username', 'Phone_Number', 'email', 'gender', 'birth_date', 'password1', 'password2')


    def clean_Phone_Number(self):
        '''
        take some cleaning on user phone number before registration
        '''
        Phone_Number = self.cleaned_data['Phone_Number']

        if Phone_Number[:4] != "+251":
                raise forms.ValidationError("Invalid phone number country code!(+251)")
        else:
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(Phone_Number=Phone_Number)
            except Account.DoesNotExist:
                return Phone_Number
            raise forms.ValidationError('Phone Number "%s" is already in use.' % Phone_Number)


    def clean_email(self):
        '''
        clean user email before sending to database
        on registration
        '''
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError(f'Email {email} is already in use.')

    def clean_username(self):
        '''
        clean username before sending to database
        on registration
        '''
        username = self.cleaned_data['username']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            return username
        raise forms.ValidationError(f'Username {username} is already in use.')

class UserUpdateForm(forms.ModelForm):
    '''
    Model form for username update
    '''
    class Meta:
        model   = Account
        fields  = ['first_name', 'last_name','username']
        email   = forms.EmailField()

class ProfilePicUploadForm(forms.ModelForm):
    '''
    Model form for profile picture upload and update
    '''
    class Meta:
        model   = ProfilePic
        fields  = ["image", ]

class BioUpdateForm(forms.ModelForm):
    '''
    Model form for username update
    '''
    class Meta:
        model   = UserBio
        fields  = ['bio',]

explainit/accounts/views.py
from django.shortcuts import (render, 
								redirect,
								get_object_or_404,
								)
from .forms import (AccountCreationForm, 
					UserUpdateForm,
					ProfilePicUploadForm,
					)
from django.contrib import messages
from django.contrib.auth import login, authenticate, get_user_model
from .models import TermsOfService
from django.views.generic import (ListView, 
									CreateView, 
									UpdateView,
									DetailView,
									)
from django.contrib.auth.decorators import login_required
from .models import ProfilePic
from django.contrib.auth.mixins import (LoginRequiredMixin,
										UserPassesTestMixin,
										)
from accounts.models import Account

#ACCOUNT-ACTIVATION
from .tokens import AccountActivationToken
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage



def AccountActivationView(request, uidb64, token):
	try:
		uid = int(force_str(urlsafe_base64_decode(uidb64)))
		user = Account.objects.get(pk=uid)
		print(user)
	except:
		user = None

	if user is not None and AccountActivationToken.check_token(user, token):
		user.is_active = True
		user.save()

		messages.success(request, "Thank you for your email confirmation. Now you can login your account.")
		return redirect('accounts:login-page')
	else:
		messages.error(request, "Activation link is invalid!")

	return redirect('homepage:homepage')

def sendEmail(request, user, to_email):
	mail_subject = "Activate your user account."
	message = render_to_string("accounts/account_activation_page.html", {
		'user': user.username,
		'domain': get_current_site(request).domain,
		'uid': urlsafe_base64_encode(force_bytes(user.pk)),
		'token': AccountActivationToken.make_token(user),
		"protocol": 'https' if request.is_secure() else 'http'
	})
	email = EmailMessage(mail_subject, message, to=[to_email])
	if email.send():
		messages.success(request, f'Check your email to activate your account.')
	else:
		messages.error(request, f'Problem sending email to {to_email}, check if you typed it correctly.')


def AccountCreationPageView(request, *args, **kwargs):
	"""A FUNCTION FOR USER REGISTRATION 
		AUTHENTICATED USER HAVE NO PERMISSION TO ACCESS REGISTRATION PAGE
		UNLESS LOGGED OUT!!!
	"""
	if request.user.is_authenticated:
		messages.info(request, f'Logout first!!')
		return redirect('homepage:homepage')
	else:
		if request.method == 'POST':
			form = AccountCreationForm(request.POST)
			if form.is_valid():
				user = form.save()
				email = form.cleaned_data.get('email')
				sendEmail(request, user, email)

				return redirect('homepage:homepage')            
		else:
			form = AccountCreationForm()
		return render(request, 'accounts/account_creation_page.html', {'form': form})


class TermsOfServiceListView(ListView):
	'''
	class based view to show list of terms of service of explainit
	@ListView: django builtin class based view
	'''
	model 			= TermsOfService
	template_name 	= 'accounts/terms_of_service.html'

	def get_context_data(self, *args, **kwargs):
		'''
		returns what to send to the template
		'''
		context = super(TermsOfServiceListView, self).get_context_data(*args, **kwargs)
		context['title'] = "ExplainIT-terms of service"
		context['terms_of_services'] = TermsOfService.objects.all()
		return context

@login_required
def UserProfileHomeView(request):
	context = {}

	if request.user.is_authenticated:
		user_image = request.user.profile_pic.image.url
		context['user_image'] = user_image
	'''
	A function to manage user profile homepage
	'''
	current_user = request.user
	template = 'accounts/user_profile_home.html'
	return render(request, template, context)

@login_required
def UpdateUserProfile(request):
	'''
	a function to update user name 
	'''
	if request.method == 'POST':
		user_account_form = UserUpdateForm(request.POST, instance=request.user)
		if user_account_form.is_valid():
			user_account_form.save()
			messages.success(request, f'Your name has been updated!')
			return redirect('accounts:user-profile-home-view')
	else:
		user_account_form = UserUpdateForm(instance=request.user)
	
	context = {
		'user_account_form': user_account_form
    	}
	return render(request, 'accounts/account_profile_update.html', context)

class ProfilePicUpdateView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
	'''
	class based view to update the pp
	'''

	model = ProfilePic
	form_class = ProfilePicUploadForm
	template_name = 'profile_pic/profile_picture_update_view.html'

	def get_context_data(self, *args, **kwargs):
		'''
		returns a context that needs to be sent to template
		'''
		context = super(ProfilePicUpdateView, self).get_context_data(*args, **kwargs)
		context['title'] = f'{self.request.user} - Update profile picture'
		return context

	def test_func(self):
		'''
		authorization function, tests if the current user is
		the author of the pp
		'''
		profile_pic = self.get_object()
		if self.request.user == profile_pic.user:
			'''if profile_pic.image.url:
				profile_pic.image.delete(save=True)
			'''
			return True
		return False


class AccountDetailView(DetailView):

	model = Account
	template_name = 'accounts/account_detail_view_page.html'


	def get_context_data(self, *args, **kwargs):
		'''
		returns what to send to the template
		'''
		other_user = get_object_or_404(Account, pk=self.kwargs.get('pk'))
		context = super(AccountDetailView, self).get_context_data(*args, **kwargs)
		context['title'] = "ExplainIT-About"
		context['other_user'] = other_user
		return context

@login_required
def followunfollow(request, pk):
    if request.method == 'GET':
        user = request.user
        account = get_object_or_404(Account, pk=pk)

        if account.followers.filter(id=user.id).exists():
            #user has already enrolled the course
            #remove followers frpm enrolled student list
            account.followers.remove(user)
            message=messages.success(request,f'You stopped following {account.full_name}')
        else:
            account.followers.add(user)
            message =messages.success(request, f'You started following {account.full_name}')
            followers = {'total_followers':account.followers}
            return redirect(request.META.get('HTTP_REFERER'))
    return redirect(request.META.get('HTTP_REFERER'))

explainit/accounts/templates/accounts/account_activation_page.html
{% autoescape off %}
Hello {{ user.full_name }} welcome to Explain-IT,

Please click on the link below to confirm your registration and acivate your account

{{ protocol }}://{{ domain }}{% url 'accounts:activate-account' uidb64=uid token=token %}
{% endautoescape %}

explainit/accounts/templates/accounts/account_creation_page.html
{% extends 'homepage/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block mainbody%}
<section class="all-form-container">
	<section class="all-form-section">
			<fieldset>
				<div class="fieldset-header">

				</div>
				<hr>
				<h3>New Account</h3>
				<h3>Please complete all fields!</h3>
				<form method="POST">
					{% csrf_token %}
					{{form|crispy}}
					<div class="form-button">
						<button type="submit">Register</button>
					</div>
				</form>
				<p>Your information is secure</p>
				<p>By creating profile you agree to out <a href="{% url 'accounts:terms-of-service-page' %}">
					<strong>terms of service</strong></a>
				</p>
			</fieldset>
	</section>
</section>
{%endblock mainbody%}

explainit/accounts/templates/accounts/account_detail_view_page.html
{% extends 'homepage/base.html'%}
{% load static %}
{% block mainbody%}

<section class="profile-container">
	<div class="profile-left">
		<div class="user-pp">
			<a href="">
				<img src="{{other_user.profile_pic.image.url}}">
			</a>
			<small><a href="">{{other_user.full_name}}</a></small>
			<small>{{other_user.total_followers}}-followers</small>
			<small><a href="{% url 'accounts:account-follow-unfollow' other_user.pk %}">
			{% if user in other_user.followers.all %}
				Following/Unfollow
			{% else %}
				Follow
			{% endif %}
			</a></small>
		</div>
	</div>
	<div class="profile-right">
		<div class="profile-right-body">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
		</div>
	</div>
</section>
{% include 'accounts_snippets/account_courses.html' %}
{% endblock mainbody%}

explainit/accounts/templates/accounts/account_login_page.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block mainbody%}
<section class="all-form-container">
	<section class="all-form-section">
		<fieldset>
		<form method="POST">
				<header class="form-header">
					<h2>Login</h2>
				</header>
				<hr>
			{% csrf_token %}
			{{form}}
			<div class="form-button">
				<button type="submit">Login</button>
			</div>
			
		</form>
		<p>
			<small><a href="{% url 'password_reset'%}">Forgot password</a></small>
			<small><a href="{% url 'accounts:register-page' %}">Have no account</a></small> 
		</p>
		</fieldset>
	</section>
</section>
{%endblock mainbody%}

explainit/accounts/templates/accounts/account_profile_update.html
{% extends 'homepage/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block mainbody%}
<section class="all-form-container">
	<section class="all-form-section">
			<fieldset>
				<h3>Account update</h3>
				<hr>
				<form method="POST">
					{% csrf_token %}
					{{user_account_form|crispy}}
					<div class="form-button">
						<button type="submit">Update</button>
					</div>
				</form>
			</fieldset>
	</section>
</section>
{%endblock mainbody%}

explainit/accounts/templates/accounts/terms_of_service.html
{% extends 'homepage/base.html' %}
{% block mainbody%}
{% for term_item in terms_of_services %}
	<h1>{{term_item.title|safe}}</h1>
	<p>{{term_item.terms_of_service|safe}}</p>
{% endfor %}
<a href="">Agree and continue to login</a>
{% endblock mainbody %}

explainit/accounts/templates/accounts/user_profile_home.html
{% extends 'homepage/base.html'%}
{% load static %}

{% block mainbody%}

<section class="profile-container">
	<div class="profile-left">
		<div class="user-pp">
			<a href="{% url 'accounts:user-profile-pic-update-view' user.pk %}">
			<img src="{{user_image}}">
			</a>
			<small><a href="{% url 'accounts:user-profile-update-view'%}">{{user.first_name}} {{user.last_name}}</a></small>
			<small><a href="">{{user.total_followers}}-followers</a></small>
		</div>
	</div>
	<div class="profile-right">
		<div class="profile-right-body">
			
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
		</div>
	</div>
</section>
{% include 'accounts_snippets/user_detail.html' %}
{% endblock mainbody%}